config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resource :home, :only => [:index]
  resource :courses do
    resources :semesters do
      resources :videos 
    end
  end

  # post 'courses/create', :to => 'courses#create', :as => 'course_create'
  get 'courses', :to => 'courses#index', :as => 'courses_all'
  get 'courses/:id/new' => 'courses#new_semester', :as => 'course_new_semester'

  post 'courses/semesters/create', :to => 'courses#create_semester', :as => 'course_semester_create'

  root to: 'home#index'

  # TODO replace
  get 'box', :to => 'box#index', :as => 'box'
  # get 'box/auth', :to => 'box#auth', :as => 'box_auth'
  get 'box/dashboard', :to => 'box#dashboard', :as => 'box_dashboard'
  get 'box/download/:id', :to => 'box#download', :as => 'box_download'
  post 'box/upload', :to => 'box#upload', :as => 'box_upload'

  get 'drive', :to => 'drive#index', :as => 'drive'  

  get 'youtube', :to => 'youtube#index', :as => 'youtube'
  post 'youtube/upload', :to => 'youtube#upload', :as => 'youtube_upload'

  get 'process', :to => 'videos#index', :as => 'process'
  post 'process', :to => 'videos#upload', :as => 'process_upload'
end

app/models/semester.rb
class Semester < ApplicationRecord
	belongs_to :course
	has_many :videos
	has_many :professors
end

app/controllers/semesters_controller.rb
class SemestersController < ApplicationController
	def new
		byebug
		@course = Course.find(params[:id])
	end

	def update
		course = Course.find(params[:course][:id])
		if !course.nil?
			year = params[:semester][:year]
			semester = if !course.semesters.empty? then course.semesters.find(:year => year) else nil end
			if semester.nil?
				semester = course.semesters.new(:year => year)
				if semester.save!
					flash[:success] = "Semester successfully added!"
					redirect_to courses_all_path
				else
					flash[:error] = "Failed to create semester"
					redirect_to courses_all_path
				end
			end
		end
	end

	def show
		@semester = Semester.find(params[:id])
		@course = @semester.course
		@videos = @semester.videos
	end

end

app/helpers/semesters_helper.rb
module SemestersHelper
end

app/views/semesters/new.html.haml
- content_for :body do
	.container
		%h1 New Instance
		= form_for @course, courses_semester_path do |course|
			.form-container
				.form-grid
					.col-xs-8.col-md-8.no-left-padding
						= label :semester, :year, 'Year (Case sensitive eg. SP18)'
						= text_field :semester, 'year', class: 'form-control inline-block'
					%br
					= hidden_field(:course, :id, :value => @course.id)
					.col-xs-8.col-md-8.no-left-padding
						= submit_tag 'Create', class: 'btn btn-default inline-block'

app/views/semesters/show.html.haml
- content_for :body do
	.container	
		%h1=@course.title + " " + @semester.year
	.container
		%h3 Test Upload Video
		= link_to "new", new_courses_semester_video_path(@semester.id)
		%h3 Videos
		- @videos.each do |video|
			.well
				%h5=video.title
				%p=video.description
				%p=video.created_at