config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resource :home, :only => [:index]
  resource :courses do
    resources :semesters do
      resources :videos 
    end
  end

  # post 'courses/create', :to => 'courses#create', :as => 'course_create'
  get 'courses', :to => 'courses#index', :as => 'courses_all'
  get 'courses/:id/new' => 'courses#new_semester', :as => 'course_new_semester'

  post 'courses/semesters/create', :to => 'courses#create_semester', :as => 'course_semester_create'

  root to: 'home#index'

  # TODO replace
  get 'box', :to => 'box#index', :as => 'box'
  # get 'box/auth', :to => 'box#auth', :as => 'box_auth'
  get 'box/dashboard', :to => 'box#dashboard', :as => 'box_dashboard'
  get 'box/download/:id', :to => 'box#download', :as => 'box_download'
  post 'box/upload', :to => 'box#upload', :as => 'box_upload'

  get 'drive', :to => 'drive#index', :as => 'drive'  

  get 'youtube', :to => 'youtube#index', :as => 'youtube'
  post 'youtube/upload', :to => 'youtube#upload', :as => 'youtube_upload'

  get 'process', :to => 'videos#index', :as => 'process'
  post 'process', :to => 'videos#upload', :as => 'process_upload'
end

app/models/video.rb
class Video < ApplicationRecord
	belongs_to :semester

	def get_folder
		return "/#{get_parent_folder}#{self.number}"
	end		

	def get_parent_folder
		return "/#{self.course.abbrev}/#{self.course.year}"
	end

	def get_full_path
		return "/#{get_folder}#{self.path}"
	end	

	def get_local_parent_folder
		return "#{Rails.root.to_s}/public/#{get_parent_folder}"
	end

	def get_local_folder
		return "#{Rails.root.to_s}/public/#{get_folder}"
	end	

	def get_path
		return "#{get_local_folder}/#{self.path}"
	end
end

app/controllers/videos_controller.rb
Faraday.default_adapter = :httpclient
Faraday::Response.register_middleware :gzip => Faraday::Response::Middleware

class VideosController < ApplicationController	
	include GoogleHelper
	include YoutueHelper
	include ProcessHelper

	def video_params 
		params.require(:video).permit(:title, :description, :category_id, :tags, :category_id, :number, :id)
	end

	def semester_params
		params.require(:semester).permit(:id)
	end

	def drive_params
		params.require(:drive).permit(:file_path)
	end

	# Assumes video already exists on box
	# def upload
	# 	course = Course.find_by :year => course_params[:year], :code => course_params[:code]
	# 	box_video_id ||= params[:video][:box_video_id]
	# 	box_video_path ||= params[:video][:box_video_path]
	# 	# fix this
	# 	video_params[:tags] = video_params[:tags].split(',').map { |tag| 
	# 		tag.downcase
	# 	}
	# 	video = course.videos.build(video_params)
	# 	status, message = find_and_upload_to_yt(box_video_id, box_video_path, course, video, video_params)
	# 	if status == 1
	# 		redirect_to process_path, :flash => { :success => message }
	# 	else
	# 		redirect_to process_path, :flash => { :warning => message }
	# 	end
	# end

	# TODO: Youtube does not accept service accounts, need to use oauth on octo account
	def upload
		drive = get_drive
		semester = Semester.find semester_params[:id]
		video = Video.find semester_params[:video_id]
		tags = extract_tags(video.tags)

		params = video_params
		params[:tags] = tags

		status = upload_to_yt(video_params, video)
		# TODO Flash success or failure
	end

	def edit

	end

	def new
		@semester = Semester.find(params[:semester_id])
		@course = Course.find(@semester.course.id)
	end

	def create
		semester = Semester.find(params[:semester_id])
		video = semester.videos.new(video_params)
		upload_to_drive(semester, video, drive_params[:file_path])
		redirect_to new_courses_semester_video_path(semester.id), :flash => { :success => "File successfully uploaded! "}
		# TODO Flash success or failure
	end
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/videos/index.html.haml
- content_for :head do
	= stylesheet_link_tag 'dashboard'

- content_for :body do
	.container
		%h1 Video Processing Dashboard
		.no-left-padding
			%p This current form is used to simulate the type of requests that the backend would usually process in the automated pipeline. Ideally, Plugging in SD card into Raspberry Pi triggers upload to Box via a script, followed by sending a request to the Hermione backend which creates the models and uploads it to Youtube.
		= form_for :video, :semester => {:controller => 'videos', :action => 'process/upload'} do |f|
			.form-container
				.upload-form-grid
					.c1
						= label :semester, :id, 'Semester Id'
						= text_field :semester, 'id', class: 'form-control inline-block'
					.c2
						= label :semester, :video_id, 'Video Id'
						= text_field :semester, 'video_id', class: 'form-control inline-block'
					.v3
						= label :video, :title, 'Video Title'
						= text_field :video, 'title', class: 'form-control inline-block'
					.v4
						= label :video, :category_id, 'Category ID'
						= text_field :video, 'category_id', class: 'form-control inline-block'
					.desc
						= label :video, :description, 'Description'
						= text_area :video, 'description', class: 'form-control inline-block'
					.tags
						= label :video, :tags, 'Tags'
						= text_field :video, 'tags', class: 'form-control inline-block'
									
				.col-xs-12.col-md-12.no-left-padding
					%br
					= submit_tag 'Upload', class: 'btn btn-default inline-block'

app/views/videos/new.html.haml
- content_for :head do
	= stylesheet_link_tag 'dashboard'

- content_for :body do
	.container
		%h1= "New Video for " + @course.abbrev
		%p Internal tool meant for uploading a file to google drive from a service account
		= form_for :video, :url => courses_semester_videos_path(@semester.id) do |f|
			.form-container
				.upload-form-grid
					.v1
						= label :video, :number, 'Video Number'
						= text_field :video, 'number', class: 'form-control inline-block'
					.v2
					.v3
						= label :video, :title, 'Video Title'
						= text_field :video, 'title', class: 'form-control inline-block'
					.v4
						= label :video, :category_id, 'Category ID'
						= text_field :video, 'category_id', class: 'form-control inline-block'
					.desc
						= label :video, :description, 'Description'
						= text_area :video, 'description', class: 'form-control inline-block'
					.tags
						= label :video, :tags, 'Tags'
						= text_field :video, 'tags', class: 'form-control inline-block'
					.local
						= label :drive, :file_path, 'File Path'
						= text_field :drive, 'file_path', class: 'form-control inline-block'
									
				.col-xs-12.col-md-12.no-left-padding
					%br
					= submit_tag 'Upload', class: 'btn btn-default inline-block'