config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resource :home, :only => [:index]
  resource :courses do
    resources :semesters do
      resources :videos 
    end
  end

  # post 'courses/create', :to => 'courses#create', :as => 'course_create'
  get 'courses', :to => 'courses#index', :as => 'courses_all'
  get 'courses/:id/new' => 'courses#new_semester', :as => 'course_new_semester'

  post 'courses/semesters/create', :to => 'courses#create_semester', :as => 'course_semester_create'

  root to: 'home#index'

  # TODO replace
  get 'box', :to => 'box#index', :as => 'box'
  # get 'box/auth', :to => 'box#auth', :as => 'box_auth'
  get 'box/dashboard', :to => 'box#dashboard', :as => 'box_dashboard'
  get 'box/download/:id', :to => 'box#download', :as => 'box_download'
  post 'box/upload', :to => 'box#upload', :as => 'box_upload'

  get 'drive', :to => 'drive#index', :as => 'drive'  

  get 'youtube', :to => 'youtube#index', :as => 'youtube'
  post 'youtube/upload', :to => 'youtube#upload', :as => 'youtube_upload'

  get 'process', :to => 'videos#index', :as => 'process'
  post 'process', :to => 'videos#upload', :as => 'process_upload'
end

app/controllers/box_controller.rb
require 'rest-client'
require 'boxr'
require 'open-uri'
require 'json'

class BoxController < ApplicationController
    include BoxAuth
    before_action :require_client, only: [:get_box_client]

    # BUG: Navigating to box/dashboard before authentication
    def require_client
        unless $client
            redirect_to box_auth_path
        end
    end

    def save_box_token(access, refresh)
        BoxToken.create(:token => refresh)
    end

    def upload
        placeholder = "videos" # temporary
        url = params[:url][:path]
        folder_id = params[:url][:folder_id]
        client = get_box_client 

        folder = client.folder_from_id(folder_id)
        if not folder
            redirect_to box_dashboard_path, :flash => { :warning => "Invalid folder."}
            return
        end
        upload_file_path = "#{Rails.root.to_s}/public/#{placeholder}/#{url}"
        if File.file?(upload_file_path)
            status = nil
            begin 
                status = upload_video_box(upload_file_path, folder)
            rescue Boxr::BoxrError
                redirect_to box_dashboard_path, :flash => { :error => "Upload failed."}
                return
            end
            redirect_to box_dashboard_path, :flash => { :success => "Successfully uploaded file!"}
            return
        else
            redirect_to box_dashboard_path, :flash => { :warning => "Invalid file."}
            return
        end
    end

    def download
        client = get_box_client 

        file = client.file_from_id(params[:id])
        file_path = get_file_path(file)
        folder_path = get_folder_path(file)

        url = client.download_url(file)

        check_path(folder_path)
        if not File.file?(file_path)
            open(file_path, 'wb') do |file|
                file << open(url).read
            end
            redirect_to box_dashboard_path, :flash => { :success => "File successfully downloaded! "}
        else
            redirect_to box_dashboard_path, :flash => { :warning => "File already exists. "}
        end
    end

    def dashboard
        client = get_service_account
        @client_id = client.client_id
        @folders = client.root_folder_items
        @folder_items = {}
        @folders.each do |folder| 
            @folder_items[folder.id] = client.folder_items(folder)
        end
    end

    def index
        @code = params[:code]
        @state = params[:state]
        @client = get_service_account
        if @client
            redirect_to box_dashboard_path
        end
    end

    # def auth 
        # res = HTTP.follow.get('https://account.box.com/api/oauth2/authorize', :params => {
        #         response_type: 'code',
        #         client_id: ENV['BOX_CLIENT_ID'],
        #         redirect_uri: "http://localhost:3000/box",
        #         state: 'pineapple'
        #     })
        # redirect_to res.uri.to_s
    # end
end

app/helpers/box_helper.rb
module BoxHelper
end

app/views/box/dashboard.html.haml
- content_for :head do
	= stylesheet_link_tag 'dashboard'

- content_for :body do
	.container
		%h1 Box API Dashboard
		= form_for :video, :url => {:controller => 'box', :action => 'upload'} do |f|
			.form-container
				.form-grid
					.col-xs-12.col-md-12.no-left-padding
						= label :url, :path, 'File name'
						= text_field :url, 'path', class: 'form-control inline-block'
					.col-xs-12.col-md-12.no-left-padding
						= label :url, :folder_id, 'Folder ID'
						= text_field :url, 'folder_id', class: 'form-control inline-block'
					.col-xs-12.col-md-12.no-left-padding
						= submit_tag 'Upload', class: 'btn btn-default inline-block'
		%table.table
			%thead
				%tr
					%th Name
					%th ID
					%th Files
			%tbody
				- @folders.each do |folder|
					%tr
						%th 
							= folder.name
						%td 
							= folder.id
						%td
							- @folder_items[folder.id].take(5).each do |file|
								.files
									%p
										= file.name
									%p
										= link_to "Download", box_download_path(file.id)

app/views/box/index.html.haml
- content_for :body do
	.container
		%h1 Box API
		%p 
			= @code
		%p 
			= @state
		%p
			= @client

		= link_to "Authenticate", box_auth_path