config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resource :home, :only => [:index]
  resource :courses do
    resources :semesters do
      resources :videos 
    end
  end

  # post 'courses/create', :to => 'courses#create', :as => 'course_create'
  get 'courses', :to => 'courses#index', :as => 'courses_all'
  get 'courses/:id/new' => 'courses#new_semester', :as => 'course_new_semester'

  post 'courses/semesters/create', :to => 'courses#create_semester', :as => 'course_semester_create'

  root to: 'home#index'

  # TODO replace
  get 'box', :to => 'box#index', :as => 'box'
  # get 'box/auth', :to => 'box#auth', :as => 'box_auth'
  get 'box/dashboard', :to => 'box#dashboard', :as => 'box_dashboard'
  get 'box/download/:id', :to => 'box#download', :as => 'box_download'
  post 'box/upload', :to => 'box#upload', :as => 'box_upload'

  get 'drive', :to => 'drive#index', :as => 'drive'  

  get 'youtube', :to => 'youtube#index', :as => 'youtube'
  post 'youtube/upload', :to => 'youtube#upload', :as => 'youtube_upload'

  get 'process', :to => 'videos#index', :as => 'process'
  post 'process', :to => 'videos#upload', :as => 'process_upload'
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
	include GoogleHelper

	def course_params
        params.require(:course).permit(:title, :code, :year, :abbrev, :description)
    end

    def course_semester_params
    	params.require(:semester).permit(:year)
    end

	def new
	end

	def edit

	end

	def show
		@courses = Course.all
	end

	def update

	end

	def destroy

	end

	def detail
		@course = Course.find(params[:id])
	end

	def index
		@courses = Course.all
	end

	# create new course
	def create
		found = Course.find_by_title_and_year(params[:course][:title], params[:course][:year])

		# Handle redirects and flashing
		if found.nil?
			c = Course.create!(course_params)
			byebug
			upload_to_drive(c)
		end
		redirect_to root_path
	end

	def new_semester
		@course = Course.find(params[:id])
		render :new_semester
	end

end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/views/courses/new.html.haml
- content_for :body do
	.container
		%h1 New Course
		= form_for :course, url: courses_path do |f|
			.form-container
				.form-grid
					.col-xs-12.col-md-12.no-left-padding
						= label :course, :title, 'Course Title'
						= text_field :course, 'title', class: 'form-control inline-block'
					.col-xs-12.col-md-12.no-left-padding
						= label :course, :code, 'Code'
						= text_field :course, 'code', class: 'form-control inline-block'
					.col-xs-12.col-md-12.no-left-padding
						= label :course, :year, 'Year'
						= text_field :course, 'year', class: 'form-control inline-block'
					.col-xs-12.col-md-12.no-left-padding
						= label :course, :abbrev, 'Abbreviation'
						= text_field :course, 'abbrev', class: 'form-control inline-block'
					.col-xs-12.col-md-12.no-left-padding
						= label :course, :description, 'Description'
						= text_area :course, 'description', class: 'form-control inline-block'
					%br
					.col-xs-12.col-md-12.no-left-padding
						= submit_tag 'Create', class: 'btn btn-default inline-block'

app/views/courses/new_semester.html.haml
- content_for :body do
	.container
		%h1="New semester of " + @course.abbrev
		= form_for @course, :url => {:controller => "courses", :action => "create_semester"} do |course| 
			.form-container
				.form-grid
					.col-xs-8.col-md-8.no-left-padding
						= label :semester, :year, 'Year (Case sensitive eg. SP18)'
						= text_field :semester, 'year', class: 'form-control inline-block'
					%br
					= hidden_field(:course, :id, :value => @course.id)
					.col-xs-8.col-md-8.no-left-padding
						= submit_tag 'Create', class: 'btn btn-default inline-block'

app/views/courses/show.html.haml
- content_for :body do
	.container
		%h1 Courses
		- @courses.each do |course|
			.well
				%h4=course.abbrev
				%h5=course.title
				%p Semesters
				- course.semesters.each do |semester|
					%p
						= link_to semester.year, courses_semester_path(semester.id)
				= link_to "new", course_new_semester_path(course.id)